# Generated by Django 3.2.5 on 2021-07-10 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('name', models.CharField(max_length=255, verbose_name='Budget name')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='date created')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='date updated')),
                ('transfer_type', models.CharField(choices=[('INCOME', 'Income'), ('OUTCOME', 'Outcome')], max_length=255, verbose_name='Transfer type')),
                ('monetary_units', models.PositiveIntegerField(verbose_name='Monetary units (e.g. 10$==1000 monetary units, cents)')),
                ('currency', models.CharField(max_length=3, verbose_name='Currency iso alpha 3')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='Description of the transfer')),
                ('budget', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transfers', to='budget.budget')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
