# Generated by Django 3.2.5 on 2021-07-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget', '0003_auto_20210710_0854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('CAD', 'CAD'), ('UAH', 'UAH')], max_length=3, verbose_name='Currency iso alpha 3'),
        ),
    ]
